"""update comment relationships

Revision ID: 2a694274d994
Revises: 41fd0abb7058
Create Date: 2025-03-27 20:44:02.774479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a694274d994'
down_revision = '41fd0abb7058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reply_to_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reply_to_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reply_to_user_id')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
