"""Add parent_id and reply_to_user_id to forum posts

Revision ID: 41fd0abb7058
Revises: 
Create Date: 2025-03-27 19:31:13.703641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fd0abb7058'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reply_to_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'forum_posts', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reply_to_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reply_to_user_id')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
