"""add views to content

Revision ID: 4f8b2a9c1234
Revises: 3e4bf8c6ef40
Create Date: 2025-03-29 15:12:32.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8b2a9c1234'
down_revision = '3e4bf8c6ef40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('views', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'views')
    # ### end Alembic commands ###
